/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.itson.interfazGrafica;

import com.itson.dominio.Licencia;
import javax.persistence.EntityManagerFactory;
import javax.swing.ImageIcon;

/**
 * Clase que representa la ventana para seleccionar el tipo de trámite
 * de placas.
 */
public class SelectAutoFrm extends javax.swing.JFrame {

    /**
     * EntityManagerFactory para la conexión de la base de datos.
     */
    private EntityManagerFactory emf;
    
    /**
     * Licencia de la persona que realiza el trámite.
     */
    private Licencia licPersona;
    
    /**
     * Referencia de la ventana anterior.
     */
    private BusquedaLicFrm anterior;

    /**
     * Constructor de la clase SelectAutoFrrm.
     * @param anterior Ventana anterior.
     * @param lic Licencia de la persona que raliza el trámite.
     * @param emf EntityManagerFactory para la conexión de la base de datos.
     */
    public SelectAutoFrm(BusquedaLicFrm anterior, Licencia lic, EntityManagerFactory emf) {
        initComponents();
        this.emf = emf;
        licPersona = lic;
        this.anterior = anterior;
        gobIcon.setIcon(new ImageIcon("src/main/resources/LogoGob.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblGobmx = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblInicio = new javax.swing.JLabel();
        btmAutoNuevo = new javax.swing.JButton();
        btmAutoUsado = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btmRegresar1 = new javax.swing.JButton();
        gobIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 400));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(11, 35, 30));

        lblGobmx.setText("Gob.mx");
        lblGobmx.setFont(new java.awt.Font("Sitka Subheading", 1, 18)); // NOI18N
        lblGobmx.setForeground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(19, 50, 43));

        lblInicio.setText("Tramite de placas");
        lblInicio.setFont(new java.awt.Font("Sitka Subheading", 1, 18)); // NOI18N
        lblInicio.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblInicio)
                .addContainerGap(426, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(lblInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btmAutoNuevo.setText("Automovil nuevo");
        btmAutoNuevo.setBackground(new java.awt.Color(157, 36, 73));
        btmAutoNuevo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(157, 36, 73), 5));
        btmAutoNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btmAutoNuevo.setFocusable(false);
        btmAutoNuevo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btmAutoNuevo.setForeground(new java.awt.Color(255, 255, 255));
        btmAutoNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmAutoNuevoActionPerformed(evt);
            }
        });

        btmAutoUsado.setText("Automovil usado");
        btmAutoUsado.setBackground(new java.awt.Color(157, 36, 73));
        btmAutoUsado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(157, 36, 73), 5));
        btmAutoUsado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btmAutoUsado.setFocusable(false);
        btmAutoUsado.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btmAutoUsado.setForeground(new java.awt.Color(255, 255, 255));
        btmAutoUsado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmAutoUsadoActionPerformed(evt);
            }
        });

        btmRegresar1.setText("Regresar");
        btmRegresar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(157, 36, 73), 3));
        btmRegresar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btmRegresar1.setFocusable(false);
        btmRegresar1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btmRegresar1.setForeground(new java.awt.Color(157, 36, 73));
        btmRegresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmRegresar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(382, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1)
                            .addComponent(btmAutoUsado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btmAutoNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btmRegresar1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btmAutoNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btmAutoUsado, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(btmRegresar1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        gobIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LogoGob.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(gobIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblGobmx)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gobIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblGobmx)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método de acción del botón para ir al trámite de placas para autos usados.
     * @param evt Evento de acción.
     */
    private void btmAutoUsadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmAutoUsadoActionPerformed
        // TODO add your handling code here:
        new PlacaUsadoFrm(emf, licPersona, this).setVisible(true);
        dispose();
    }//GEN-LAST:event_btmAutoUsadoActionPerformed

    /**
     * Método de acción del botón para ir al trámite de placas para autos nuevos.
     * @param evt Evento de acción.
     */
    private void btmAutoNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmAutoNuevoActionPerformed
        // TODO add your handling code here:
        new PlacaNuevaFrm(emf, licPersona, this).setVisible(true);
        dispose();
    }//GEN-LAST:event_btmAutoNuevoActionPerformed

    /**
     * Método de acción del botón "Regresar".
     * @param evt Evento de acción.
     */
    private void btmRegresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmRegresar1ActionPerformed
        regresar();
    }//GEN-LAST:event_btmRegresar1ActionPerformed

    /**
     * Método privado para regresar a la ventana anterior.
     */
    private void regresar() {
        this.anterior.setVisible(true);
        this.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmAutoNuevo;
    private javax.swing.JButton btmAutoUsado;
    private javax.swing.JButton btmRegresar1;
    private javax.swing.JLabel gobIcon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblGobmx;
    private javax.swing.JLabel lblInicio;
    // End of variables declaration//GEN-END:variables
}
